### ISSUE TITLE
Links to each training are broken

### ISSUE THREAD

**Issue by baroncurtin2** [DomoApps/sdk-training#10]
Hi Domo,
The links to each of the trainings are broken (Easy - Legendary). Would you be able to look into it please? I was using the legendary training so that I could setup Webpack with the proxy.
Thanks

**Comment by jgalb** [comment]
@sldavidson @walexnelson are you guys looking into this?

**Comment by walexnelson** [comment]
@baroncurtin2 the training site has been taken down now that Domopalooza is complete. We'll be moving the content to a more long-term home such as the [dev portal](developer.domo.com). This repo will also be taken down at the end of the week. 

If you've already cloned this repo then you actually already have access to the training documentation. It's found under `/docs` and has some instructions for running a local jekyll server if you don't want to read the markdown documentation.
